services:
  fastapi:
    container_name: fastapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: app/Dockerfile
    # 이미지 실행 명령어
    # Alembic 마이그레이션 및 uvicorn 실행
    entrypoint: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./media:/app/media
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      - mysql
      - redis

  ai-worker:
    container_name: ai-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./media:/app/media:ro
      # 모델은 마운트하여 이미지 경량화
      - ./worker/models:/app/worker/models:ro
    depends_on:
      - redis

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


volumes:
  mysql_volume:
