upstream fastapi {
    server fastapi:8000;
}

server {
    server_name 54.180.119.228;
    listen 80;

    location /static/ {
        root /vol/web;
    }

    location /media/ {
        root /vol/web;
    }

    location / {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }
}
